name: Permadeath
version: 1.3
main: tech.layon.permadeath.Main

load: STARTUP
api-version: '26.3'

authors:
  - LAYON
  - SebazCRC
  - vo1d_dev

description: Versión adaptada y actualizada por LAYON para NegativeStudios, desarrollada sobre la base original de PermadeathCore de SebazCRC.

website: https://github.com/MrLion303/PermadeathCoreRebirth

softdepend:
  - WorldEdit
  - SkinsRestorer

commands:
  pdc:
    description: Comando principal de Permadeath
    aliases:
      - permadeath
